name: Build

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.22.* ]
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Download Golang dependencies to /vendor
        uses: make vendor

      - name: Building
        uses: make build
