name: lint

on: [push, pull_request]

jobs:
  lint:
    strategy:
      matrix:
        go-version: [ 1.22.* ]
        os: [ macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
