name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.22.* ]
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Download Golang dependencies to /vendor
        run: make vendor

      - name: Building
        run: make build

      - name: Testing
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  test-goos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: true
      # https://go.dev/doc/install/source#environment
      - run: GOOS=darwin GOARCH=amd64 go test -c -v ./...
      - run: GOOS=darwin GOARCH=arm64 go test -c -v ./...
      - run: GOOS=linux GOARCH=386 go test -c -v ./...
      - run: GOOS=linux GOARCH=amd64 go test -c -v ./...
      - run: GOOS=linux GOARCH=arm go test -c -v ./...
      - run: GOOS=linux GOARCH=arm64 go test -c -v ./...
      - run: GOOS=windows GOARCH=amd64 go test -c -v ./...
      - run: GOOS=windows GOARCH=386 go test -c -v ./...
      - run: GOOS=windows GOARCH=arm go test -c -v ./...
      - run: GOOS=windows GOARCH=arm64 go test -c -v ./...
